// <auto-generated />
using System;
using Calculator.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator.API.Migrations
{
    [DbContext(typeof(CalculationDbContext))]
    [Migration("20240407150946_CreateCalculationHistoryTable")]
    partial class CreateCalculationHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Calculator.Domain.Entities.CalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calculation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TImestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalculationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
